 CREATE TABLE [Users] (
	Id int NOT NULL,
	Name nvarchar(100) NOT NULL UNIQUE,
	Login nvarchar(100) NOT NULL UNIQUE,
	Password nvarchar(100) NOT NULL UNIQUE,
  CONSTRAINT [PK_USER] PRIMARY KEY CLUSTERED
  (
  [Id] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [Events] (
	Id int NOT NULL,
	Name nvarchar(100) NOT NULL,
	Info nvarchar(500) NOT NULL,
	Date date NOT NULL,
	Time time NOT NULL,
	UserId int NOT NULL,
  CONSTRAINT [PK_EVENTS] PRIMARY KEY CLUSTERED
  (
  [Id] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [Reminders] (
	Id int NOT NULL,
	EventId int NOT NULL,
  CONSTRAINT [PK_REMINDERS] PRIMARY KEY CLUSTERED
  (
  [Id] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [Alarms] (
	Id int NOT NULL,
	Name nvarchar(100) NOT NULL,
	UserId int NOT NULL,
	Time time NOT NULL,
  CONSTRAINT [PK_ALARMS] PRIMARY KEY CLUSTERED
  (
  [Id] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO

ALTER TABLE [Events] WITH CHECK ADD CONSTRAINT [Events_fk0] FOREIGN KEY ([UserId]) REFERENCES [User]([Id])
ON UPDATE CASCADE
GO
ALTER TABLE [Events] CHECK CONSTRAINT [Events_fk0]
GO

ALTER TABLE [Reminders] WITH CHECK ADD CONSTRAINT [Reminders_fk0] FOREIGN KEY ([EventId]) REFERENCES [Events]([Id])
ON UPDATE CASCADE
GO
ALTER TABLE [Reminders] CHECK CONSTRAINT [Reminders_fk0]
GO

ALTER TABLE [Alarms] WITH CHECK ADD CONSTRAINT [Alarms_fk0] FOREIGN KEY ([UserId]) REFERENCES [User]([Id])
ON UPDATE CASCADE
GO
ALTER TABLE [Alarms] CHECK CONSTRAINT [Alarms_fk0]
GO